# Notebook 1: Programming and Python Fundamentals

*Quantitative Methods in Neuroscience, Master in Neuroscience, University of Geneva (2026-27)*

Welcome to the very first hands-on session of the course! This notebook walks you through the **Python building blocks** that every subsequent practical will rely on. By the end of it you should feel comfortable opening a notebook, typing some code, running it, reading errors, and putting together a small piece of Python from scratch.

> If you have never installed Python before, follow the illustrated setup guide sent before the first practical (`QMN_setup_guide_students.pdf`, also in the course folder together with `SETUP_INSTRUCTIONS.txt`). Make sure the `qmn` conda environment is created and selected as the kernel of this notebook (top-right corner of VS Code). The TAs will walk through the install.

### By the end of this notebook you will be able to:
- Navigate a Jupyter notebook (cells, kernel, shortcuts).
- Use the words **library**, **module**, **function**, **argument** and **method** correctly.
- Use **variables**, **basic types**, and **arithmetic**.
- Use **lists**, **tuples**, **dictionaries** and **f-string** formatting.
- Write **conditionals** (`if`/`elif`/`else`) and **loops** (`for`/`while`).
- Recognise a Python **function call** and explain what its inputs and outputs mean.
- Read a Python **error traceback** and understand what it says.
- Read and write a **text file** from Python.
- **Import** modules and use the built-in help.
- Load a table with **pandas** and look at what is inside it.
- Apply all of the above to a small first analysis, written by hand.

### Table of contents

1. [How to use this notebook](#section-1)
2. [Jupyter mechanics](#section-2)
3. [VS Code as your IDE](#section-3)
4. [The words we will use](#section-4)
5. [Variables, basic types and functions](#section-5)
6. [Arithmetic, strings and printing](#section-6)
7. [Collections: lists, tuples, dictionaries](#section-7)
8. [Conditionals](#section-8)
9. [Loops](#section-9)
10. [Reading errors and asking for help](#section-10)
11. [Reading and writing files](#section-11)
12. [Imports and the standard library](#section-12)
13. [A first look at pandas](#section-13)
14. [Bridge exercise: a first analysis by hand](#section-14)
15. [Capstone: a small report, written by hand](#section-15)
16. [What comes next](#section-16)

> **How to read this notebook.** Markdown cells like this one explain the *concept*. Code cells implement it. Look out for **`▶ Task`** boxes: those are short exercises where you have to edit or extend the code, each tagged by difficulty:
>
> - **⭐** essential for everyone: run the code, understand it, change it slightly.
> - **⭐⭐** intermediate: repair a small bug, complete the missing lines, write a short function.
> - **⭐⭐⭐** optional challenge: build a fuller piece of analysis on your own.
>
> A few cells are **deliberately broken**, and say so: running them and reading the error is the exercise. If you get stuck, ask the TAs. If you use AI help, treat it as a tutor, not as a replacement for thinking: you should still be able to read each line of code and explain what it does. We have prepared a custom GPT bot tuned for this course: https://chatgpt.com/g/g-69fc9bfc9a748191a912a124800d9254-qmn-teaching-assistant-bot


## A 2-minute warm-up: what is programming?

If you have never written a line of code before, no worries: this notebook is built exactly for you. Two ideas in plain language before we start.

- **A computer is a very fast, very literal "employee".** It does exactly what you tell it to do, in exactly the order you tell it, and stops at the first thing it does not understand. "Programming" is the act of *writing down* instructions for that employee.
- **Python is a language for those instructions**, chosen here because its rules (i.e. syntax) are concise, its scientific libraries are excellent, and most neuroscience labs use it day-to-day. You will not need to *memorize* all of this immediately: you will pick them up by reading code, modifying it, and seeing what changes.

A **Jupyter notebook** (the file you are reading) is a sequence of *cells*. Some cells, like this one, contain **text**. Others contain **Python code** that you can run by clicking on the cell and pressing `Shift+Enter`. You will see your first runnable code cell in a moment.


<a id="section-1"></a>
## 1. How to use this notebook

Each section introduces one Python building block, then asks you to use it on a small problem. The recipe is always the same:

1. **Read** the markdown cell that explains the concept.
2. **Run** the code cell (`Shift+Enter`) and look at the output.
3. **Tweak** the code: change a value, add a `print`, see what changes.
4. **Do the `▶ Task`** at the end of the section by editing the `# TODO` cell.

Don't be afraid to break things in this notebook, that is *how* you learn.

> **Note.** This notebook is deliberately shallow but wide: we touch on each concept just enough to be able to *read* and *modify* the code in the following notebooks (Math Refresher, Statistics, …). We will revisit each topic in greater depth when we need it. For more resources on Python see the relevant section of the course materials page.


<a id="section-2"></a>
## 2. Jupyter mechanics

A Jupyter notebook (the type of file you are reading) is a sequence of **cells** of two kinds:

- **Markdown cells** (like this one) contain *text*. They are rendered into nicely formatted prose, lists, tables, equations, etc. Double-click on a markdown cell to edit it, then `Shift+Enter` to render.
- **Code cells** contain *Python code*. `Shift+Enter` runs the cell; whatever it produces (numbers, plots, errors) appears just below.

Behind the scenes, a **kernel** (the small Python process attached to the notebook) keeps in memory the variables you define alive across cells. So a variable created in one cell can be reused in a later cell. **This means the *order* in which you run cells matters.** If something looks wrong, the safe move is *Kernel → Restart Kernel and Run All*: it gives you a fresh slate and re-runs every cell in order.

Run the next cell: it should print a message and show that things are alive. It uses `print(...)`, which displays whatever you put between the parentheses underneath the cell. Section 4 says a little more about what that means.


In [1]:
# --- A first code cell. Pressing Shift+Enter on this cell runs it.
print("Hello, QMN! Your kernel is alive.")
2 + 2  # The last expression of a cell is automatically displayed below.

Hello, QMN! Your kernel is alive.


4

> **▶ Task 2.1 ⭐ - Make yourself at home.**
> 1. Edit the markdown cell below to introduce yourself in three bullet points (name, background, one neuroscience topic that fascinates you). Use `**bold**` for your name and `*italics*` somewhere.
> 2. Insert a brand-new code cell *below* the markdown cell (`Esc`, then `B`), and use it to print the result of `7 * 6`.


*Replace this text with your three bullet points.*

<a id="section-3"></a>
## 3. VS Code as your IDE (quick orientation)

VS Code is the editor we recommend for the course, and the window you are reading this in. You do not need any of what follows to get through the notebook, but knowing that these exist will save you time from today on.

**A note on keyboard shortcuts.** Every shortcut below has a button or a menu entry that does the same thing, and each bullet says where it is. Shortcuts differ between Windows, macOS and Linux, they can be remapped, and extensions sometimes take them over, so if one does nothing on your machine, use the button and move on.

Three features make the difference between "writing code in a notebook" and "doing data analysis like a pro":

- **Run cell, run everything above.** Every code cell has a small play button on its left; the toolbar at the top of the notebook has **Run All**, and the `...` menu next to it has *Run All Above* and *Run All Below*. Running one cell at a time is the normal way to work, and *Run All Above* is what you want after changing something in the middle. From the keyboard, `Shift+Enter` runs the cell and moves to the next one, `Ctrl+Enter` runs it and stays where you are. The same toolbar carries two buttons worth knowing from the start: **Restart**, which throws away everything the kernel is holding so that no variable survives, and **Clear All Outputs**, which removes the printed results and the figures while leaving your code alone. *Restart* followed by *Run All* is the standard cure when a notebook starts behaving strangely because its cells were run out of order.
- **The variable inspector.** Click **Variables** in the notebook toolbar and a panel opens listing everything currently alive in the kernel, with the **name** and the **type** of each one.
- **The integrated terminal.** `Ctrl` and the backtick key opens a terminal *inside* VS Code, already in the project folder, and **Terminal**, then **New Terminal** in the top menu does the same. From there you can run `conda activate qmn`, `python --version`, and so on, without leaving the editor.

Two more features that we will meet in later weeks:

- **Breakpoint debugging.** Hover just left of a line number and a red dot appears; click it to set a breakpoint, then run the cell in debug mode, from the small arrow next to the run button or with *Debug Cell*. Execution stops at that line and you can look at every variable at that instant, which is how you find out what is happening *inside* a function.
- **The side bar.** The icons down the left edge switch between the panels: **Explorer** for the files of the course folder, **Search** to find a word across all of them, **Run and Debug** for what the previous bullet describes, and **Source Control**, which shows what you have changed recently in your code repository (we will discuss this more in detail later).

The TAs will demo these live during the practical. Come back to this section once you have written a few cells: it will mean more then.

<a id="section-4"></a>
## 4. The words we will use

Four words come up in every cell from here on, and they are easy to mix up. Two minutes now saves a lot of confusion later.

- A **function** is a named piece of code that does a job for you. You **call** it by writing its name followed by parentheses: `print("hello")`.
- Whatever you put between those parentheses is an **argument**: the input you hand to the function. Some functions take none, some take one, some take several separated by commas.
- A **module** is one file of Python code. A **library** (also called a **package**) is a collection of modules that belong together and are installed as one thing.
- Base Python does not know how to read a spreadsheet or draw a figure. Those abilities come from libraries such as `pandas` and `matplotlib`, which you make available with an `import` (section 12). The `qmn` environment you built for the course already contains every library we need, so you never have to install anything by hand.

There is a fifth word, **method**, which we will meet in section 7.2, once we have an object to point at.

In [2]:
# --- Function calls: the name, then the arguments in parentheses
print("one argument")
print("several", "arguments", "separated by commas")   # print puts a space between them

# Some functions give you a value back, which you can store in a variable
rounded = round(3.14159, 2)     # two arguments: the number, and how many decimals to keep
print("round(3.14159, 2) gives", rounded)

# A function with no arguments at all still needs its parentheses
print()                          # prints an empty line

one argument
several arguments separated by commas
round(3.14159, 2) gives 3.14



**The three kinds of brackets.** Python gives each pair a different job, and mixing them up is one of the most common early errors:

| Bracket | Used for | Example |
|---------|----------|---------|
| `( )` | calling a function, and grouping arithmetic | `print(x)`, `2 * (3 + 4)` |
| `[ ]` | building a list, and picking an element out of one | `[1, 2, 3]`, `rts[0]` |
| `{ }` | building a dictionary, and holding values inside an f-string | `{"S01": 24}`, `f"{x}"` |

**One convention to remember from the start: Python counts from 0.** The first element of a list is at position `0`, the second at position `1`, and the last one of a list of length `n` is at position `n - 1`. This catches everybody at least once, and it is behind one of the errors we will read together in section 10.

<a id="section-5"></a>
## 5. Variables, basic types and functions

A **variable** is a *name* you give to a *value*, so you can reuse the value later in your code. Think of it as a labelled box: the **label** is the name (on the left of `=`), and the **box** holds the value (on the right of `=`).

Let's create the simplest variable possible: a counter that holds the number `240`.


In [3]:
# --- Our very first variable
n_trials = 240    # the value 240 is assigned to the name "n_trials"
print(n_trials)   # later we can ask Python to print whatever n_trials currently holds

240


So far we used an integer (`240`). But a variable can hold many other kinds of values: decimal numbers, text, truth values, or "nothing" (a placeholder). The kind of value is called the **type**. You can ask Python what type a value has with the built-in `type()` function. Let's create a variable of each common type and inspect it:


In [4]:
# --- Some variables of different types
n_subjects = 12             # int   : how many animals took part
mean_rt    = 0.485          # float : a reaction time, in seconds
subject_id = "S01"          # str   : a label for one animal, made up here
is_correct = True           # bool  : did it get the trial right
not_set    = None           # NoneType: nothing recorded yet

print(n_subjects, type(n_subjects))
print(mean_rt,    type(mean_rt))
print(subject_id, type(subject_id))
print(is_correct, type(is_correct))
print(not_set,    type(not_set))

12 <class 'int'>
0.485 <class 'float'>
S01 <class 'str'>
True <class 'bool'>
None <class 'NoneType'>


**Reference: the basic types you'll meet in this course:**

| Type        | Example             | Represents                |
|-------------|---------------------|---------------------------|
| `int`       | `12`                | integer numbers           |
| `float`     | `3.14`              | real numbers (decimal)    |
| `str`       | `"hello"`           | text (a "string")         |
| `bool`      | `True` / `False`    | truth values              |
| `NoneType`  | `None`              | "nothing here yet"        |

**Naming conventions.** Use **descriptive** names in `snake_case` (lowercase words separated by underscores): `mean_rt`, `n_trials`, `subject_id`. The name of a variable should ideally tell something about its meaning (this will make your code more readable by you and others). Avoid single letters except for short throwaway counters like `i`, `j`. It is also good practice to comment the code you write describing in words what each line does (after a `#` symbol in Python).


You can **reassign** a variable at any time: Python does not care what type the new value has:

In [5]:
# --- A variable can be reassigned (and its type can even change)
x = 10 # after this line, x holds the integer value 10
print(x, type(x)) # print the value and type of x
x = "ten" # after this line, x holds the string value "ten"
print(x, type(x)) # print the value and type of x again (notice how it changed)

10 <class 'int'>
ten <class 'str'>


> **▶ Task 5.1 ⭐ - Declare and print.**
> Create three variables of your choice (one of each: `int`, `float`, `str`), and print each one followed by its type, in this format:
>
> ```text
> value = 42 <class 'int'>
> ```


In [6]:
# TODO 5.1 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
my_int   = 42
my_float = 3.14
my_str   = "neuron"

print("value =", my_int, type(my_int))
print("value =", my_float, type(my_float))
print("value =", my_str, type(my_str))
# --- END SOLUTION


value = 42 <class 'int'>
value = 3.14 <class 'float'>
value = neuron <class 'str'>


`type()` is another **function**, like `print()` and `round()` in section 4: we give it a variable as *input*, and it *returns* (gives back) the type of that variable.

Remember the general shape: a function is a reusable piece of code that takes some inputs and returns an output, ***function_name(inputs) = output***.

We will see in greater depth how functions work and how you can define your own functions further in this course.

<a id="section-6"></a>
## 6. Arithmetic, strings and printing

### 6.1 Arithmetic operators

The simplest thing you can do in Python is treat it as a calculator. Try the cell below: each line is one calculation, and Python prints the result.


In [7]:
# --- A quick numerical playground
print(3 + 4)
print(7 / 2)
print(7 // 2)
print(7 % 2)
print(2 ** 10)
print(2 * (3 + 4))

7
3.5
3
1
1024
14


**Reference: arithmetic operators**

| Symbol | Operation         | Example               |
|--------|-------------------|-----------------------|
| `+`    | addition          | `3 + 4 → 7`           |
| `-`    | subtraction       | `3 - 4 → -1`          |
| `*`    | multiplication    | `3 * 4 → 12`          |
| `/`    | division          | `7 / 2 → 3.5`         |
| `//`   | integer division  | `7 // 2 → 3`          |
| `%`    | modulo (remainder) | `7 % 2 → 1`          |
| `**`   | exponent          | `2 ** 10 → 1024`      |

Parentheses work as in mathematics: `2 * (3 + 4)` is `14`, while `2 * 3 + 4` is `10` (operator precedence is the same as you learn in school for mathematical operators).


### 6.2 Strings and f-strings

A **string** is a sequence of characters surrounded by quotes (single `'…'` or double `"…"`, both work; pick one and stay consistent).

The single most useful tool for *combining text with values* is the **f-string**: a string prefixed with `f` in which any `{expression}` inside braces is replaced by the value of that expression. You will use f-strings constantly:


In [8]:
# --- f-strings
subject = "S01"      # one animal identifier
n_trials = 1440      # how many trials it did
mean_rt  = 0.4853    # its average reaction time, in seconds

# Anything inside {...} inside an f-string is replaced by its value:
print(f"Subject {subject} ran {n_trials} trials with mean RT {mean_rt:.3f} s.")

# The :.3f after mean_rt means "format as a float with 3 decimals".
# Other useful format specifiers:
print(f"{mean_rt:.0f}")     # round to nearest integer
print(f"{mean_rt * 100:.1f}%")  # percentage, 1 decimal
print(f"{n_trials:,}")      # thousands separator

Subject S01 ran 1440 trials with mean RT 0.485 s.
0
48.5%
1,440


> **▶ Task 6.1 ⭐ - A small calculation.**
> A behavioural experiment has 8 sessions of 45 minutes each, and on average the subject completes 1 trial every 3 seconds. Use Python expressions to compute and print, with f-strings:
> 1. Total number of trials across all sessions.
> 2. Number of trials per minute (rounded to one decimal).
> 3. Average duration of one session in hours (rounded to two decimals).


In [9]:
# TODO 6.1 - your code here
n_sessions       = 8
minutes_per_session = 45
seconds_per_trial   = 3


# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
trials_per_minute = 60 / seconds_per_trial
trials_total      = n_sessions * minutes_per_session * trials_per_minute
hours_per_session = minutes_per_session / 60

print(f"Total trials:           {trials_total:,.0f}")
print(f"Trials per minute:      {trials_per_minute:.1f}")
print(f"Session duration (h):   {hours_per_session:.2f}")
# --- END SOLUTION


Total trials:           7,200
Trials per minute:      20.0
Session duration (h):   0.75


<a id="section-7"></a>
## 7. Collections: lists, tuples, dictionaries

Real data are rarely a single number: you usually have *many* of them, often labelled. Python ships with three workhorse containers.

### 7.1 Lists

A **list** is an ordered, mutable (= modifiable) collection of values. You write it with **square brackets** and commas. Lists can contain anything, even values of different types.


In [10]:
# --- Lists
subjects = ["S01", "S02", "S03"]          # three animals, with made-up labels
rts      = [0.41, 0.55, 0.62, 0.39, 0.48]  # five reaction times, in seconds

print(subjects)
print("length:", len(subjects))          # number of elements
print("first :", subjects[0])            # indexing is 0-based!
print("last  :", subjects[-1])           # negative index = from the end
print("slice :", rts[1:4])               # elements 1, 2, 3 (4 excluded)

['S01', 'S02', 'S03']
length: 3
first : S01
last  : S03
slice : [0.55, 0.62, 0.39]


### 7.2 Methods and attributes

In Python, everything is an **object**: a number, a string, a list, a dictionary, everything (Python is an object oriented language). Think of an object as a thing in the real world: it can *do* something (its **methods**) and it can *have* properties (its **attributes**). Each object comes with two kinds of "tools" that you access through a `.` (the **dot operator**):

- **Methods** are *functions that belong to the object*. You call them *with* parentheses: `object.method_name(arguments)`.
- **Attributes** are *pieces of data stored inside the object*. You read them *without* parentheses: `object.attribute_name`.

This is the minimum "object-oriented programming" vocabulary you need to get through the rest of the course. You will see the ***object.something()*** pattern everywhere, again in section 13 when we meet `pandas` (`df.head()`, `df.describe()`), and from Week 2 onwards with `numpy` (`array.mean()`, `array.shape`).

Let's start with **list methods**. A list comes with a small toolbox for modifying itself *in place*:


In [11]:
# --- List methods: modifying a list in place
subjects = ["S01", "S02", "S03"]        # the same three animals as above
print("start    :", subjects)

subjects.append("S04")                  # add an element at the end
print("append   :", subjects)

last = subjects.pop()                   # remove AND return the last element
print("pop      :", subjects, "→ removed:", last)

subjects.insert(1, "S00")               # insert at a given position
print("insert   :", subjects)

subjects.sort()                         # sort in place (alphabetically here)
print("sort     :", subjects)

subjects.reverse()                      # reverse in place
print("reverse  :", subjects)

# A method that *returns* a value rather than modifying in place:
print("count S01:", subjects.count("S01"))

start    : ['S01', 'S02', 'S03']
append   : ['S01', 'S02', 'S03', 'S04']
pop      : ['S01', 'S02', 'S03'] → removed: S04
insert   : ['S01', 'S00', 'S02', 'S03']
sort     : ['S00', 'S01', 'S02', 'S03']
reverse  : ['S03', 'S02', 'S01', 'S00']
count S01: 1


Notice the difference between the two flavours of methods:

- `subjects.append("S04")` returns nothing: it *modifies the list in place*. Trying to write `result = subjects.append("S04")` would assign `None` to `result`, which is a *very* common beginner trap.
- `subjects.pop()` and `subjects.count(...)` *return a value* you can capture with `=`.

When in doubt, check the docs, or try it once with ***print(object.method())*** to see what comes back.

Now to **attributes**. Lists happen not to have any that you would use, but most other objects do, and the scientific libraries are full of them. A date is the clearest example: it *stores* a year and a month, and it can *work out* which weekday it falls on. The first two are attributes, the third is a method, and the parentheses are what tell them apart:


In [12]:
# --- Attributes are read without parentheses, methods are called with them
from datetime import date

first_practical = date(2026, 9, 17)     # a date object: it stores a year, a month and a day

print("the date  :", first_practical)
print("its year  :", first_practical.year)      # attribute: data already inside the object
print("its month :", first_practical.month)     # attribute again, so no parentheses
print("weekday   :", first_practical.weekday()) # method: it works something out, so parentheses
print("(0 is Monday, so 3 means Thursday)")

the date  : 2026-09-17
its year  : 2026
its month : 9
weekday   : 3
(0 is Monday, so 3 means Thursday)


> **▶ Task 7.1 ⭐ - Lists in motion.**
> Start from this list:
>
> ```python
> letters = ["b", "d", "a"]
> ```
>
> Using only the list methods you just met (`.append()`, `.sort()`, `.pop()`, `.reverse()`):
>
> 1. Append `"c"` to the list.
> 2. Sort the list alphabetically.
> 3. Pop the last element of the list and store it in a variable; print it.
> 4. Reverse what remains.
> 5. Print the final list.


In [13]:
# TODO 7.1 - your code here
letters = ["b", "d", "a"]


# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
letters.append("c")
letters.sort()
last_letter = letters.pop()
print("popped:", last_letter)
letters.reverse()
print("final :", letters)
# --- END SOLUTION


popped: d
final : ['c', 'b', 'a']


**One trap worth knowing now.** Assigning a list to a second name does **not** copy it: both names point at the same list, so changing one changes the other. When you want an independent copy, ask for one with `.copy()`.

In [14]:
# --- Two names for one list, and how to get a real copy
original = ["S01", "S02"]       # two animals again, the content does not matter here
same_list = original            # NOT a copy: another name for the same list
real_copy = original.copy()     # an independent copy

original.append("S03")

print("original :", original)
print("same_list:", same_list)   # changed too, because it is the same list
print("real_copy:", real_copy)   # unchanged

original : ['S01', 'S02', 'S03']
same_list: ['S01', 'S02', 'S03']
real_copy: ['S01', 'S02']


### 7.3 Dictionaries

A **dictionary** (or `dict`) maps **keys** to **values**, and keeps them in the order you added
them. You write it with **curly braces** and `key: value` pairs separated by commas. Use a dict when you want to *look up* a value by a label.

In [15]:
# --- Dictionaries
subject_age = {"S01": 24, "S02": 31, "S03": 28}   # three subjects and their age in years

print(subject_age)
print("age of S02:", subject_age["S02"])
print("subjects  :", list(subject_age.keys()))
print("ages      :", list(subject_age.values()))

# Add or update an entry:
subject_age["S04"] = 22
print(subject_age)

{'S01': 24, 'S02': 31, 'S03': 28}
age of S02: 31
subjects  : ['S01', 'S02', 'S03']
ages      : [24, 31, 28]
{'S01': 24, 'S02': 31, 'S03': 28, 'S04': 22}


### 7.4 Tuples

A **tuple** looks like a list but uses **parentheses** and is **immutable**: once created, its contents cannot be changed. You'll typically meet tuples in two situations: as small fixed bundles of values (e.g. an `(x, y)` coordinate), or as the return value of a function that returns several things at once. For now, just be aware they exist. In section 15 you will use one as a **dictionary key**, which is something a list cannot do precisely because a list can change.

```python
point = (0.3, 0.85)   # an (x, y) tuple: point[0] is 0.3, point[1] is 0.85
```


> **▶ Task 7.2 ⭐ - Build your own collections.**
> 1. Create a list called `contrasts` containing the values `-0.5, -0.25, 0.0, 0.25, 0.5`. These are real stimulus levels from the dataset we will use all term: the sign says which side the stimulus was on, the size says how easy it was to see.
> 2. Print the length of the list, its first element and its last element.
> 3. Create a dictionary called `mouse_group` mapping `"CSHL045"`, `"CSHL046"`, `"CSP001"` to `"WT"`, `"WT"`, `"ASD"`. Print the group of mouse `"CSP001"`. Those are real animal identifiers from a dataset we will use, and the two labels mean wild type, the ordinary kind of mouse, and the line used as a model of autism.


In [16]:
# TODO 7.2 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
contrasts = [-0.5, -0.25, 0.0, 0.25, 0.5]
print("length:", len(contrasts))
print("first :", contrasts[0])
print("last  :", contrasts[-1])

mouse_group = {"CSHL045": "WT", "CSHL046": "WT", "CSP001": "ASD"}
print("group of CSP001:", mouse_group["CSP001"])
# --- END SOLUTION


length: 5
first : -0.5
last  : 0.5
group of CSP001: ASD


<a id="section-8"></a>
## 8. Conditionals

A **conditional** runs different code depending on whether some condition is true. The basic structure is:

```python
if condition_1:
    # runs only if condition_1 is True
elif condition_2:
    # runs only if condition_1 was False AND condition_2 is True
else:
    # runs if all the above were False
```

The `elif` and `else` branches are optional. Indentation matters in Python: the body of each branch must be **indented** (press `tab` on your keyboard to indent).

<img src="assets/01/ifelse.png" width="470">

*The conditions are checked in order. The first one that is true runs its own block and the rest are skipped, which is why the order you write them in matters. If none is true, the `else` block runs.*

### Comparison and logical operators

| Operator | Meaning                  | Example         |
|----------|--------------------------|-----------------|
| `==`     | equal to                 | `x == 0`        |
| `!=`     | not equal to             | `x != 0`        |
| `<`, `>` | less / greater than      | `x > 0.5`       |
| `<=`, `>=` | less / greater or equal | `x <= 1`       |
| `and`    | both must be true        | `0 < x and x < 1` |
| `or`     | at least one must be true | `x < 0 or x > 1` |
| `not`    | flips a boolean          | `not x > 0`     |


Before the first `if`, one word about what a comparison actually produces. `signed_contrast > 0` is
not a question Python asks: it is an **expression that returns a value**, either `True` or `False`.
That value is a **boolean**, the fourth type from section 5, and you can store it, print it and
count it like any other.

In [17]:
# --- A comparison is a value
contrast = 0.25                    # how visible the stimulus was: 0 means nothing to see

is_visible = contrast > 0          # store the answer in a variable
print(is_visible, type(is_visible))

# Booleans count as 1 and 0, which is how you count how many times something is true
answers = [True, False, True, True]
print("correct answers:", sum(answers), "out of", len(answers))


True <class 'bool'>
correct answers: 3 out of 4


In [18]:
# --- Classify a trial by how strong its stimulus was
# In the dataset we use all term, one number describes the stimulus of a trial: its sign says
# which side it appeared on, and its size says how visible it was. 0 means nothing was shown.
signed_contrast = 0.0625

# abs() is a built-in function that drops the sign: abs(-0.5) and abs(0.5) are both 0.5.
# We use it here because the side does not change how hard the trial is.

if abs(signed_contrast) >= 0.5:
    difficulty = "easy"
elif abs(signed_contrast) >= 0.125:
    difficulty = "medium"
elif signed_contrast == 0:
    difficulty = "zero contrast (nothing to see on either side)"
else:
    difficulty = "hard"

print(f"signed contrast = {signed_contrast:+.4f}  →  {difficulty}")

signed contrast = +0.0625  →  hard


> **▶ Task 8.1 ⭐ - Side classifier.**
> Write a small piece of code that, given a value of `signed_contrast`:
> - prints `"stimulus on the right"` if `signed_contrast > 0`,
> - prints `"stimulus on the left"` if `signed_contrast < 0`,
> - prints `"zero contrast"` if `signed_contrast == 0`.
>
> Test it for at least three different values. The stimulus levels in the real dataset are `0`, `±0.0625`, `±0.125`, `±0.25`, `±0.5` and `±1`.


In [19]:
# TODO 8.1 - your code here
signed_contrast = -0.25   # NB: you can change this value to test different cases

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
if signed_contrast > 0:
    msg = "stimulus on the right"
elif signed_contrast < 0:
    msg = "stimulus on the left"
else:
    msg = "zero contrast"
print(f"signed contrast = {signed_contrast:+.4f}  →  {msg}")
# --- END SOLUTION


signed contrast = -0.2500  →  stimulus on the left


<a id="section-9"></a>
## 9. Loops

A **loop** repeats the same operation many times over:

- a `for` loop repeats an action for each item in a sequence;
- a `while` loop repeats an action **as long as a condition is true**.

<img src="assets/01/forwhileloop.jpeg" width="620">

*The difference in one picture. A `for` loop stops when it runs out of items, a `while` loop stops when its condition becomes false, which is why a `while` whose condition never changes runs forever.*

### 9.1 `for` loops

The most common loop iterates over a list (or any "iterable"):


In [20]:
# --- Loop over a list and process each element
subjects = ["S01", "S02", "S03"]    # three animals
for subj in subjects:
    print(f"now processing subject {subj}")

now processing subject S01
now processing subject S02
now processing subject S03


Often you want to loop over a range of integers. `range(n)` produces the integers `0, 1, …, n-1`. `range(start, stop)` produces `start, …, stop-1`. `range(start, stop, step)` adds a stride.

In [21]:
# --- range()
for i in range(5):
    print(i)
print("---")
for i in range(2, 10, 2):    # 2, 4, 6, 8
    print(i)


0
1
2
3
4
---
2
4
6
8


Use `enumerate()` when you need **both** the index and the value:

In [22]:
# --- enumerate()
subjects = ["S01", "S02", "S03"]
for i, subj in enumerate(subjects):
    print(f"#{i}: {subj}")

#0: S01
#1: S02
#2: S03


Use `zip()` when you need to iterate over two lists in parallel:

In [23]:
# --- zip()
subjects = ["S01", "S02", "S03"]    # three subjects
ages = [24, 31, 28]                 # and their ages, in years
for subj, age in zip(subjects, ages):
    print(f"{subj} is {age} years old.")

S01 is 24 years old.
S02 is 31 years old.
S03 is 28 years old.


### 9.2 `while` loops

A `while` loop keeps repeating *as long as* a condition is true. Use it when you don't know in advance how many iterations you need:

In [24]:
# --- while loop: keep halving until below a threshold
x = 1.0
n_iter = 0
while x > 0.01:
    x = x / 2
    n_iter += 1   # short for: n_iter = n_iter + 1
print(f"reached x = {x:.4f} in {n_iter} iterations")

reached x = 0.0078 in 7 iterations


> **▶ Task 9.1 ⭐⭐ - Counting and summing.**
> Using a `for` loop:
> 1. Print all the even numbers between 0 and 20 (inclusive).
> 2. Compute the sum of squares of the integers from 1 to 10 (i.e. $1^2 + 2^2 + \dots + 10^2$). Hint: start with a variable `total = 0` and update it inside the loop.


In [25]:
# TODO 9.1 - your code here
# 1) even numbers 0..20

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
for n in range(0, 21, 2):
    print(n, end=" ")        # end=" " prints a space instead of starting a new line
print()

# 2) sum of squares
total = 0
for k in range(1, 11):
    total = total + k ** 2
print(f"sum of squares 1..10 = {total}")
# --- END SOLUTION


0 2 4 6 8 10 12 14 16 18 20 
sum of squares 1..10 = 385


### 9.3 Shorthand: list comprehensions

In real Python code (and in any AI-generated snippet you might paste), you will very quickly meet a more compact way to build a list out of a `for` loop: a **list comprehension**. The shape is:

```
[ expression   for   variable   in   iterable   if   condition ]
```

The `if condition` part is optional. Read it left to right: *"collect every value of `expression`, for every `variable` in `iterable`, keeping only those for which `condition` is true."*

There is nothing magical about it: a comprehension is just a shorter way to write a `for` loop that builds a list. Use it when it makes the code clearer; stick with a regular `for` loop when the body is more than one expression or when the logic is hard to read on a single line.


In [26]:
# --- Three ways to do the same thing, plus a dict-comprehension bonus

# (1) Classic for-loop building a list
squares = []
for n in range(10):
    squares.append(n ** 2)
print("for-loop      :", squares)

# (2) Equivalent list comprehension
squares = [n ** 2 for n in range(10)]
print("comprehension :", squares)

# (3) Comprehension with a filter: only even squares
even_squares = [n ** 2 for n in range(10) if n % 2 == 0]
print("filtered      :", even_squares)

# (4) Dict comprehensions exist too: the same syntax, with a key: value pattern
square_table = {n: n ** 2 for n in range(5)}
print("dict comp     :", square_table)


for-loop      : [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
comprehension : [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
filtered      : [0, 4, 16, 36, 64]
dict comp     : {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


<a id="section-10"></a>
## 10. Reading errors and asking for help

When your code goes wrong, Python prints a **traceback**: a multi-line error message ending with the *most informative* line. The golden rule is:

> **Read the traceback from the bottom up.** The last line tells you *what* went wrong; the lines above tell you *where*.

Let's deliberately cause five common errors and read each one carefully. (Each cell will *fail*, that's the point. Look at the error, then move on.)


In [27]:
# --- NameError: using a name that was never defined
print(my_undefined_variable)

NameError: name 'my_undefined_variable' is not defined

`NameError: name 'my_undefined_variable' is not defined`. Python looked for a variable called `my_undefined_variable` in the current kernel and couldn't find one. Either you mistyped the name, or you haven't yet run the cell that defines it. **Most common cause:** running cells out of order. *Restart Kernel → Run All* usually fixes it.

In [28]:
# --- TypeError: combining incompatible types
"trial " + 3


TypeError: can only concatenate str (not "int") to str

`TypeError: can only concatenate str (not "int") to str`. Python's `+` operator means "addition" for numbers and "concatenation" for strings, but the two cannot be mixed. The fix here is to convert the integer to a string first: `"trial " + str(3)`. Even better, use an f-string: `f"trial {3}"`.

In [29]:
# --- IndexError: asking for a position that doesn't exist
subjects = ["S01", "S02", "S03"]
print(subjects[5])


IndexError: list index out of range

`IndexError: list index out of range`. The list has 3 elements (indices 0, 1, 2), so asking for index 5 makes no sense. **Most common cause:** off-by-one. Remember that Python indexing is *0-based*: the last element of a list of length `n` is at index `n - 1` (or, equivalently, `-1`).

In [30]:
# --- SyntaxError: a line that Python cannot even read
# The colon at the end of an "if" line is not optional.
if 3 > 2
    print("three is bigger")

SyntaxError: expected ':' (1351939687.py, line 3)

`SyntaxError: expected ':'`. This one is different from the three above. Python did not even start running the cell: it could not make sense of the text. **Nothing in the cell runs**, not even the lines before the mistake. Look at the line the message points to, and at the one just above it, since a missing bracket or quote often only becomes visible on the next line.

In [31]:
# --- IndentationError: a block that is not indented
for subject in ["S01", "S02"]:
print(subject)

IndentationError: expected an indented block after 'for' statement on line 2 (648226668.py, line 3)

`IndentationError: expected an indented block`. In Python the indentation **is** the syntax. Everything that belongs inside an `if`, a `for` or a `while` has to be indented under it, by one tab or four spaces, consistently. This is the other error you will meet while typing your first loops.

### Getting help

When you need to know what a function does or which arguments it takes, two quick options inside a notebook:

```python
help(round)     # the full documentation, in the output
round?          # a quick summary (a Jupyter shortcut)
```

And of course: **read the official docs**. For the standard library, https://docs.python.org/3/library/. For NumPy, pandas, matplotlib, scipy, the project sites all have searchable references and many examples.

> **▶ Task 10.1 ⭐⭐ - Fix two broken snippets.**
> The two code cells below each contain a small bug. Read the traceback, identify the problem, and fix the code so that it runs and produces a sensible output. Do **not** silently delete code: fix the bug, then leave a short `# comment` explaining what the bug was.


In [32]:
# TODO 10.1 (a) - fix the bug
n_trials = 240
mean_rt  = 0.5

# The line below is the BROKEN version (currently commented out so the cell can run).
# Uncomment it, run the cell, read the error, then write a corrected version on
# the line below it.
# print("Subject ran " + n_trials + " trials with mean RT " + mean_rt + " s")

# Your fix here:

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
print(f"Subject ran {n_trials} trials with mean RT {mean_rt} s")
# --- END SOLUTION


Subject ran 240 trials with mean RT 0.5 s


In [33]:
# TODO 10.1 (b) - fix the bug
rts = [0.41, 0.55, 0.62, 0.39, 0.48]

# BROKEN version (commented out):
# print("last RT:", rts[len(rts)])

# Your fix here:

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
print("last RT:", rts[-1])
# --- END SOLUTION


last RT: 0.48


<a id="section-11"></a>
## 11. Reading and writing files

Sooner or later you want to keep something: a note about a session, a list of results, a small summary. Python reads and writes plain text files on its own, with no library at all.

The pattern is always the same:

```python
with open("filename.txt", mode) as f:
    ...
```

| Mode | Meaning |
|------|---------|
| `"r"` | read a file that already exists |
| `"w"` | write, creating the file or **overwriting** it |
| `"a"` | append, adding to the end of an existing file |

Always open a file with `with open(...)`: it closes the file for you when the indented block ends, even if something goes wrong inside it. The files below are created next to this notebook, so you can see them appear in the VS Code explorer on the left.

For tables with columns we use pandas instead, in section 13. `open()` is for plain text.

In [34]:
# --- Writing a plain text file
# CSHL051 is one of the mice in the course dataset. The identifiers come from the laboratories
# that trained the animals, so they look cryptic; they are just names.
notes = [
    "QMN Week 1, session notes",
    "Mouse: CSHL051",
    "Number of trials: 600",
]

with open("session_notes.txt", "w") as f:
    for line in notes:
        f.write(line + "\n")     # "\n" is the newline character, it ends the line

print("File written.")

File written.


In [35]:
# --- Reading it back
with open("session_notes.txt", "r") as f:
    content = f.read()          # the whole file, as one string

print(content)

QMN Week 1, session notes
Mouse: CSHL051
Number of trials: 600



> **Planted bug.** The next cell looks reasonable but does not run. Read the error, work out what is missing, then write the corrected version in the cell after it. This is the kind of mistake you will make ten times this term, so it is worth meeting it here.

In [36]:
# --- This cell is deliberately broken. Run it, read the error, do not fix it here.
summary = {
    "mouse": "CSHL051",
    "n_trials": 600,
    "accuracy": 0.82,
}

with open("summary.txt", "w") as f:
    for key, value in summary.items()
        f.write(f"{key}: {value}\n")

print("Summary saved.")

SyntaxError: expected ':' (3187858399.py, line 9)

> **▶ Task 11.1 ⭐⭐ - Repair it.**
> Copy the broken cell above into the cell below, fix the mistake, and run it. Then check that it worked by reading `summary.txt` back and printing it.

In [37]:
# TODO 11.1 - your corrected version here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
summary = {
    "mouse": "CSHL051",
    "n_trials": 600,
    "accuracy": 0.82,
}

# the bug was a missing ":" at the end of the "for" line
with open("summary.txt", "w") as f:
    for key, value in summary.items():
        f.write(f"{key}: {value}\n")

with open("summary.txt", "r") as f:
    print(f.read())
# --- END SOLUTION

mouse: CSHL051
n_trials: 600
accuracy: 0.82



<a id="section-12"></a>
## 12. Imports and the standard library

Python comes with a large **standard library** of modules that you can use without installing anything. Some highlights:

| Module      | What's inside                                        |
|-------------|------------------------------------------------------|
| `math`      | mathematical functions (`sqrt`, `log`, `pi`, …)       |
| `random`    | random numbers, shuffling, picking an item at random  |
| `os`        | talking to the operating system, e.g. listing a folder |
| `pathlib`   | building file paths that work on Windows, macOS and Linux |
| `csv`       | reading and writing `.csv` files by hand              |

To use a module, you `import` it. There are several flavours:


In [38]:
# --- Three equivalent ways to use math.sqrt
import math
print(math.sqrt(2))

from math import sqrt
print(sqrt(2))

from math import sqrt as square_root  # rename on import
print(square_root(2))

1.4142135623730951
1.4142135623730951
1.4142135623730951


In [39]:
# --- Three modules you will actually use in this course
import random
import os
from pathlib import Path

random.seed(0)                  # fixes the sequence, so everyone gets the same "random" result
mouse_ids = ["CSHL045", "CSHL046", "CSP001", "CSP003"]   # four real animals from the dataset
print("a mouse at random:", random.choice(mouse_ids))

here = Path.cwd()               # the folder this notebook is running from
print("running from     :", here)
print("this folder holds:", len(os.listdir(here)), "entries")

a mouse at random: CSP003
running from     : C:\Users\matteucc\Documents\QMN_course\notebooks
this folder holds: 25 entries


For the scientific stack (**NumPy**, **pandas**, **matplotlib** etc.) there are *conventional aliases* that everyone uses. You will see them everywhere, starting in section 13 of this notebook:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
```

From Week 2 on we will also import our own helper functions from the course's `src/qmn_utils.py` module:

```python
from src.qmn_utils import sigmoid
```

We will explain the `src/` folder mechanism when we get there. For now, just know that *anything you can put in a `.py` file, you can import*. That's how big projects stay organized.


> **▶ Task 12.1 ⭐ - Use the standard library.**
> Using `math`, `random` and `pathlib`, compute and print:
> 1. The value of $\sqrt{50}$.
> 2. The natural logarithm of $1000$.
> 3. The mean of the list `[0.41, 0.55, 0.62, 0.39, 0.48, 0.71]`, computed with `sum()` and `len()` rather than with a library.
> 4. One reaction time picked at random from that same list, after setting `random.seed(1)`.
> 5. The name of the folder this notebook is running from (`Path.cwd().name`).


In [40]:
# TODO 12.1 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
import math
import random
from pathlib import Path

print(f"sqrt(50)  = {math.sqrt(50):.4f}")
print(f"ln(1000)  = {math.log(1000):.4f}")

rts = [0.41, 0.55, 0.62, 0.39, 0.48, 0.71]
print(f"mean RT   = {sum(rts) / len(rts):.3f} s")

random.seed(1)
print(f"one at random = {random.choice(rts)} s")
print(f"folder    = {Path.cwd().name}")
# --- END SOLUTION


sqrt(50)  = 7.0711
ln(1000)  = 6.9078
mean RT   = 0.527 s
one at random = 0.55 s
folder    = notebooks


<a id="section-13"></a>
## 13. A first look at pandas

`pandas` is the library everyone uses to work with tables in Python. Its main object is the **DataFrame**: rows, named columns and an index, like a spreadsheet living inside Python. It is one more library, imported like any other, which is why it comes right after the standard library.

This is a first look only: load a file, see what is inside it, pull out one column. Everything else about pandas comes in Week 3.

The file we load lists the **30 mice of the IBL dataset**, one row per animal, with the laboratory that trained it and a few details. Two of its columns use shorthand you will meet all term: `group` is `WT` for a wild type animal, the ordinary kind, and `ASD` for the line used as a model of autism, and `age_weeks_at_first_session` is how old the animal was when it started training. It is the small companion to the trial by trial file we will work with from Week 3 onwards, which has almost 700,000 rows and deserves a session of its own.

In [41]:
# --- Where the course data lives.
# This works whether you opened the notebook from notebooks/ or from a subfolder of it.
from pathlib import Path

ROOT = Path.cwd() if (Path.cwd() / "data").is_dir() else Path.cwd().parent
print("ROOT =", ROOT)

import pandas as pd              # "pd" is the alias everybody uses for pandas

mice = pd.read_csv(ROOT / "data" / "ibl_2afc_subjects.csv")
print(f"loaded {mice.shape[0]} rows and {mice.shape[1]} columns")

ROOT = C:\Users\matteucc\Documents\QMN_course\notebooks


loaded 30 rows and 9 columns


### 13.1 Looking at a table

Four things are worth running on **every** new dataset, before anything else: the first rows, the size, the column names, and a summary.

In [42]:
# --- The first rows. On its own on the last line of a cell, a DataFrame is displayed as a table.
mice.head()

,subject_id,group,genotype,lab,institution,sex,birth_date,age_weeks_at_first_session,project
0,CSHL045,WT,wild-type,churchlandlab,Cold Spring Harbor Laboratory,M,2019-08-06,13,ibl_neuropixel_brainwide_01
1,CSHL046,WT,wild-type,churchlandlab,Cold Spring Harbor Laboratory,M,2019-08-06,13,ibl_neuropixel_brainwide_01
2,CSHL047,WT,wild-type,churchlandlab,Cold Spring Harbor Laboratory,M,2019-08-06,13,ibl_neuropixel_brainwide_01
3,CSHL049,WT,wild-type,churchlandlab,Cold Spring Harbor Laboratory,M,2019-08-06,13,ibl_neuropixel_brainwide_01
4,CSHL051,WT,wild-type,churchlandlab,Cold Spring Harbor Laboratory,F,2019-08-13,13,ibl_neuropixel_brainwide_01


In [43]:
# --- Size and column names
print("shape  :", mice.shape)          # (rows, columns)
print("columns:", mice.columns.tolist())

# .info() adds the type of each column and how many values are missing
mice.info()

shape  : (30, 9)
columns: ['subject_id', 'group', 'genotype', 'lab', 'institution', 'sex', 'birth_date', 'age_weeks_at_first_session', 'project']
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   subject_id                  30 non-null     str  
 1   group                       30 non-null     str  
 2   genotype                    30 non-null     str  
 3   lab                         30 non-null     str  
 4   institution                 30 non-null     str  
 5   sex                         30 non-null     str  
 6   birth_date                  30 non-null     str  
 7   age_weeks_at_first_session  30 non-null     int64
 8   project                     30 non-null     str  
dtypes: int64(1), str(8)
memory usage: 4.8 KB


In [44]:
# --- describe() summarises the numeric columns. Here there is only one.
mice.describe()

,age_weeks_at_first_session
count,30.000000
mean,11.866667
std,4.621787
min,7.000000
25%,9.000000
50%,11.000000
75%,13.000000
max,27.000000


### 13.2 One column at a time

A single column is selected by its name, in square brackets. What comes back is a **Series**: one column with its index. Two methods turn it into something you already know how to loop over:

| Method | Returns |
|--------|---------|
| `.tolist()` | the values as an ordinary Python list |
| `.unique()` | the distinct values, in order of first appearance |

Both are worth chaining: `mice["lab"].unique().tolist()` gives you a plain Python list, which prints more readably than pandas' own internal type.

In [45]:
# --- Selecting one column
ages = mice["age_weeks_at_first_session"]

print("type of one column:", type(ages))
print("first five ages   :", ages.tolist()[:5])
print()
print("labs in the file  :", mice["lab"].unique().tolist())
print("groups            :", mice["group"].unique().tolist())

type of one column: <class 'pandas.Series'>
first five ages   : [13, 13, 13, 13, 13]

labs in the file  : ['churchlandlab', 'angelakilab']
groups            : ['WT', 'ASD']


### 13.3 Rows and columns with `.loc` and `.iloc`

Most of the time you want a *piece* of the table: some rows, some columns, or only the rows that meet a condition. pandas gives you two tools, and telling them apart is the single most common source of confusion for beginners.

`.iloc` selects by **position**: "the 3rd row and the 5th column", counting from 0, exactly like list indexing. `.loc` selects by **label**: "the row labelled 3 and the column called `lab`". Both take **rows first, columns second**.

| | `.iloc` | `.loc` |
|---|---------|--------|
| **Mnemonic** | **i** for *integer* | **l** for *label* |
| **Rows** | integer positions: `0`, `5`, `0:10`, `-1` | index labels: `0`, `5`, `0:10` |
| **Columns** | integer positions: `2`, `0:4` | column **names**: `"lab"`, `["lab", "sex"]` |
| **Slice `a:b`** | **excludes** `b`, so `iloc[0:3]` gives 3 rows | **includes** `b`, so `loc[0:3]` gives 4 rows |

They look interchangeable at first, because a freshly loaded table has the index `0, 1, 2, …`, so a row's position and its label are the same number. They stop being interchangeable as soon as you filter rows, because filtering keeps the original labels.

> 📌 **Rule of thumb.** Use `.loc` by default: naming a column says what you mean, and your code keeps working if someone adds a column upstream. Use `.iloc` when position is genuinely what you mean, such as "the first row" or "the last ten". Both of them also accept a condition in place of the row numbers, which is how you filter a table, and Week 3 does exactly that.

In [46]:
# --- .iloc works with positions
print("first row, by position:")
print(mice.iloc[0])

first row, by position:
subject_id                                          CSHL045
group                                                    WT
genotype                                          wild-type
lab                                           churchlandlab
institution                   Cold Spring Harbor Laboratory
sex                                                       M
birth_date                                       2019-08-06
age_weeks_at_first_session                               13
project                         ibl_neuropixel_brainwide_01
Name: 0, dtype: object


In [47]:
# --- .loc works with labels: row label 0, column called "lab"
print("one cell, by label   :", mice.loc[0, "lab"])
print("one cell, by position:", mice.iloc[0, 3])

# rows first, columns second
mice.loc[0:2, ["subject_id", "lab", "sex"]]

one cell, by label   : churchlandlab
one cell, by position: churchlandlab


,subject_id,lab,sex
0,CSHL045,churchlandlab,M
1,CSHL046,churchlandlab,M
2,CSHL047,churchlandlab,M


> **Planted bug.** The next cell asks pandas for a column that does not exist. Run it, read the error, and notice that pandas tells you exactly which name it could not find. Then fix it in the task below.

In [48]:
# --- Deliberately broken: this column name is not in the table
print(mice["age_weeks"].mean())

KeyError: 'age_weeks'

> **▶ Task 13.1 ⭐⭐ - Fix it, then count by hand.**
> 1. Fix the broken line above: print the mean age at the first session, using the real column name.
> 2. Then, **without** using pandas beyond `.tolist()`, count how many mice each laboratory contributed: turn the `lab` column into a list, start from an empty dictionary, and add one to the right counter for every row. Print the result.

In [49]:
# TODO 13.1 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
# 1. the column is called age_weeks_at_first_session
print(f"mean age at first session: {mice['age_weeks_at_first_session'].mean():.1f} weeks")

# 2. counting by hand, with a list and a dictionary
labs = mice["lab"].tolist()

mice_per_lab = {}
for lab in labs:
    if lab not in mice_per_lab:
        mice_per_lab[lab] = 0
    mice_per_lab[lab] += 1

for lab, n in mice_per_lab.items():
    print(f"{lab}: {n} mice")
# --- END SOLUTION

mean age at first session: 11.9 weeks
churchlandlab: 10 mice
angelakilab: 20 mice


<a id="section-14"></a>
## 14. Bridge exercise: a first analysis by hand

Time to use everything you have learned so far (variables, lists, dictionaries, conditionals, loops) on a very tiny dataset. Below are 12 trials from three of the mice you met in section 13, written straight into the notebook as a **list of dictionaries**. Each dictionary is one trial: which mouse, which stimulus, what it answered, whether that was correct, and how long it took.

Two of the trials have `no_go` set to `True`: the mouse did not answer in time, so there is no `correct` value for them. Missing values like these are normal in real data, and how you handle them is a decision you have to make in every analysis.

In section 13 you loaded a real table with pandas. Here the goal is the opposite: to *feel* what the same kind of analysis looks like when you write every step by hand.


In [50]:
# --- A tiny dataset of 12 trials, hard-coded as a list of dictionaries
# One dictionary per trial. "contrast" is the stimulus, its sign giving the side and its size how
# visible it was; "response" is the side the mouse chose; "no_go" means it did not answer at all;
# "rt_s" is the reaction time in seconds.
trials = [
    {"mouse": "CSHL045", "contrast":  0.50, "response": "right", "correct": True,  "no_go": False, "rt_s": 0.42},
    {"mouse": "CSHL045", "contrast": -0.25, "response": "left",  "correct": True,  "no_go": False, "rt_s": 0.55},
    {"mouse": "CSHL045", "contrast":  0.125,"response": "right", "correct": True,  "no_go": False, "rt_s": 0.71},
    {"mouse": "CSHL045", "contrast": -0.0625,"response":"right", "correct": False, "no_go": False, "rt_s": 0.89},
    {"mouse": "CSHL046", "contrast":  0.25, "response": "right", "correct": True,  "no_go": False, "rt_s": 0.39},
    {"mouse": "CSHL046", "contrast": -0.50, "response": "left",  "correct": True,  "no_go": False, "rt_s": 0.44},
    {"mouse": "CSHL046", "contrast":  0.00, "response": None,    "correct": None,  "no_go": True,  "rt_s": 0.95},
    {"mouse": "CSHL046", "contrast": -0.125,"response": "right", "correct": False, "no_go": False, "rt_s": 0.78},
    {"mouse": "CSP001",  "contrast":  0.50, "response": "right", "correct": True,  "no_go": False, "rt_s": 0.38},
    {"mouse": "CSP001",  "contrast":  0.0625,"response":"left",  "correct": False, "no_go": False, "rt_s": 0.66},
    {"mouse": "CSP001",  "contrast": -0.25, "response": "left",  "correct": True,  "no_go": False, "rt_s": 0.52},
    {"mouse": "CSP001",  "contrast":  0.00, "response": None,    "correct": None,  "no_go": True,  "rt_s": 0.81},
]

print(f"Total trials       : {len(trials)}")
print(f"Keys of each trial : {list(trials[0].keys())}")
print(f"First trial        : {trials[0]}")

Total trials       : 12
Keys of each trial : ['mouse', 'contrast', 'response', 'correct', 'no_go', 'rt_s']
First trial        : {'mouse': 'CSHL045', 'contrast': 0.5, 'response': 'right', 'correct': True, 'no_go': False, 'rt_s': 0.42}


Let's count how many trials each mouse contributed, using a dictionary as a running tally. The pattern is: *start at zero, then for each trial, add one to the right counter*.


In [51]:
# --- Count trials per mouse
trials_per_mouse = {}
for trial in trials:
    mouse = trial["mouse"]
    if mouse not in trials_per_mouse:
        trials_per_mouse[mouse] = 0
    trials_per_mouse[mouse] += 1

for mouse, n in trials_per_mouse.items():
    print(f"{mouse}: {n} trials")


CSHL045: 4 trials
CSHL046: 4 trials
CSP001: 4 trials


And the mean reaction time of one mouse, computed by hand: sum first, then divide.


In [52]:
# --- Mean reaction time of one mouse
total_rt = 0.0
n = 0
for trial in trials:
    if trial["mouse"] == "CSHL045":
        total_rt += trial["rt_s"]
        n += 1

mean_rt = total_rt / n
print(f"CSHL045: mean RT over {n} trials = {mean_rt:.3f} s")


CSHL045: mean RT over 4 trials = 0.642 s


> **▶ Task 14.1 ⭐⭐ - Count correct vs incorrect.**
> Using a `for` loop on `trials`, count for mouse `"CSHL046"`:
> 1. The number of trials it got right (`correct` is `True`).
> 2. The number it got wrong (`correct` is `False`).
> 3. The number where it did not answer at all (`no_go` is `True`).
>
> Then compute the **accuracy** as `right / (right + wrong)`, leaving the no-go trials out of both, and print it as a percentage.


In [53]:
# TODO 14.1 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
n_correct   = 0
n_incorrect = 0
n_no_go     = 0

for trial in trials:
    if trial["mouse"] != "CSHL046":
        continue
    if trial["no_go"]:
        n_no_go += 1
    elif trial["correct"] is True:
        n_correct += 1
    else:
        n_incorrect += 1

accuracy = n_correct / (n_correct + n_incorrect)
print(f"CSHL046 - right    : {n_correct}")
print(f"CSHL046 - wrong    : {n_incorrect}")
print(f"CSHL046 - no answer: {n_no_go}")
print(f"CSHL046 - accuracy : {accuracy:.1%}")
# --- END SOLUTION


CSHL046 - right    : 2
CSHL046 - wrong    : 1
CSHL046 - no answer: 1
CSHL046 - accuracy : 66.7%


**Reflection.** Each of the analyses above took 5 to 10 lines of Python. They all share the same structure: *loop over the list, maintain counters or accumulators, compute a summary*. As datasets grow from 12 to 12,000 trials, this pattern becomes painful very quickly.

**NumPy**, in Week 2, and **pandas**, properly in Week 3, are built exactly to make this pattern disappear. As a preview, the whole "count trials per mouse" exercise above shrinks to a single line of pandas:

```python
df.groupby("mouse").size()
```

That is where we are going. But always remember: underneath, pandas is doing exactly the loops you just wrote by hand, hidden behind a friendlier interface. That is why it was worth writing them once.


<a id="section-15"></a>
## 15. Capstone: a small report, written by hand

This last exercise is optional and puts everything together. It is the kind of thing you really do with a new dataset: summarise it by group, decide what stands out, and write the result to a file that somebody else can read.

The rule of the game: **no pandas beyond `.tolist()`**. Lists, dictionaries, tuples, loops, conditionals and `open()` are enough. Doing it by hand once is what makes the one line pandas version meaningful later.

> **▶ Task 15.1 ⭐⭐⭐ - The report.**
> 1. Pull `subject_id`, `lab`, `group` and `age_weeks_at_first_session` out of `mice` as four ordinary Python lists.
> 2. Count how many mice there are in each **laboratory and group combination**, with a `for` loop. Use the pair `(lab, group)` as the dictionary key: a tuple works as a key, a list does not.
> 3. With another loop, compute the **mean age at the first session for each laboratory**. Hint: keep a running total and a count per lab, then divide at the end.
> 4. With an `if`/`else` inside a loop, sort the laboratories into `older` (mean age above 12 weeks) and `younger`.
> 5. Write one line per laboratory to `lab_report.txt`, in the form `lab: n mice, mean age x.x weeks`, then read the file back and print it.

In [54]:
# TODO 15.1 - your code here

# --- SOLUTION BELOW: TO BE REMOVED IN THE STUDENT VERSION
# 1. the four columns, as plain Python lists
subject_ids = mice["subject_id"].tolist()
labs        = mice["lab"].tolist()
groups      = mice["group"].tolist()
ages        = mice["age_weeks_at_first_session"].tolist()

# 2. how many mice in each (lab, group) combination.
# The key is a tuple, because a dictionary key has to be something that cannot change.
n_per_cell = {}
for i in range(len(subject_ids)):
    key = (labs[i], groups[i])
    if key not in n_per_cell:
        n_per_cell[key] = 0
    n_per_cell[key] += 1

for key, n in n_per_cell.items():
    lab, group = key                       # a tuple can be unpacked into two names
    print(f"{lab:<15} {group:<4} {n} mice")

# 3. mean age per lab: a running total and a count, then one division at the end
total_age = {}
n_per_lab = {}
for i in range(len(labs)):
    lab = labs[i]
    if lab not in total_age:
        total_age[lab] = 0
        n_per_lab[lab] = 0
    total_age[lab] += ages[i]
    n_per_lab[lab] += 1

mean_age = {}
for lab in n_per_lab:
    mean_age[lab] = total_age[lab] / n_per_lab[lab]

# 4. split the labs in two
older = []
younger = []
for lab in mean_age:
    if mean_age[lab] > 12:
        older.append(lab)
    else:
        younger.append(lab)

print()
print("older cohort  :", older)
print("younger cohort:", younger)

# 5. the report file
with open("lab_report.txt", "w") as f:
    for lab in n_per_lab:
        f.write(f"{lab}: {n_per_lab[lab]} mice, mean age {mean_age[lab]:.1f} weeks\n")

with open("lab_report.txt", "r") as f:
    print()
    print(f.read())
# --- END SOLUTION

churchlandlab   WT   10 mice
angelakilab     ASD  10 mice
angelakilab     WT   10 mice

older cohort  : ['churchlandlab']
younger cohort: ['angelakilab']

churchlandlab: 10 mice, mean age 13.2 weeks
angelakilab: 20 mice, mean age 11.2 weeks



<a id="section-16"></a>
## 16. What comes next

- A one page **cheat sheet** with the syntax you met today is handed out separately. Keep it next to you: for the first few weeks you will look things up constantly, and that is normal.
- **Week 2** takes the next step: writing your own functions, plotting them, and meeting NumPy arrays.
- **Week 3** gives pandas and the IBL dataset the room they deserve, and from there on every practical works with real data.

If a part of this notebook still feels shaky, come back to it before Week 2. Everything that follows is built on top of it.